dateModified: 1727277499
email:
  fromEmail: john@johnfmorton.com
  fromName: 'Bespoken Demo'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    68ac0ecb-7a50-4b09-95de-c0b89a974f4b: 'Bespoken Demo' # Bespoken Demo
    f52b004e-5cf1-4f23-a10d-619227bed996: Simple # Simple
    f81bc6e0-dc98-4e3f-b5c3-b3945417ebe7: 'Bespoken Demo' # Bespoken Demo
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Bespoken Demo'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
